# Generated by Django 2.0.5 on 2018-05-24 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True, verbose_name='Chapter Name')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True, verbose_name='Course Name')),
                ('Duration', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Duration')),
                ('NumChapters', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Number of Chapters')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_Date', models.DateField(verbose_name='Exam Date')),
                ('Time', models.PositiveIntegerField(verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ('Exam_Date',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=500, verbose_name='Header')),
                ('Difficulty', models.CharField(choices=[('1', 'simple'), ('2', 'difficult')], max_length=1, verbose_name='Difficulty')),
                ('Objective', models.CharField(choices=[('1', 'reminding'), ('2', 'understanding'), ('3', 'creativity')], max_length=1, verbose_name='Objective')),
                ('Ans1', models.CharField(max_length=500, verbose_name='Answer 1')),
                ('Ans2', models.CharField(max_length=500, verbose_name='Answer 2')),
                ('Ans3', models.CharField(max_length=500, verbose_name='Answer 3')),
                ('CorrectAns', models.CharField(max_length=500, verbose_name='Correct Answer')),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Chapter')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('Header',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('Lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('Email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('Address', models.CharField(max_length=150, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ('Email',),
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='Questions',
            field=models.ManyToManyField(to='app.Question'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course'),
        ),
    ]
