# Generated by Django 2.0.5 on 2018-05-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Chapter Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Course Name'),
        ),
    ]
