# Generated by Django 2.0.5 on 2018-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180524_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Course',
        ),
    ]
